/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gcc_util_FaceRecognize */

#ifndef _Included_gcc_util_FaceRecognize
#define _Included_gcc_util_FaceRecognize
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gcc_util_FaceRecognize
 * Method:    FaceRecognition
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gcc_util_FaceRecognize_FaceRecognition
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
