/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gcc_util_FaceAlignment */

#ifndef _Included_gcc_util_FaceAlignment
#define _Included_gcc_util_FaceAlignment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gcc_util_FaceAlignment
 * Method:    faceAlignment
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gcc_util_FaceAlignment_faceAlignment
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
